apiVersion: v1
kind: Service
metadata:
  name: myapp-service          # ✅ name must be here
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

